### ISSUE TITLE
Checklist for v4.0

### ISSUE THREAD

**Issue by Libbum** [JuliaDynamics/Agents.jl#318]
Please add when you notice something.

- [x] API simplification (#317)
- [x] CompartmentSpace (#313)
- [x] Benchmarking Suite (#299)
- [x] Update documentation front page (latest news, features)
- [x] Developer documentation page for Space API
- [x] Resolve #320 
- [x] Changelog: graph space is mutable
- [x] Some documentation links are missing with all this churn
- [x] Does the docstring of ContinuousSpace discuss `spacing` tuning?
- [x] Version bump Project.toml
- [x] Just making a note here that we should re-run benchmarks and update the relevant documentation page just before we tag v4. Things may be slightly different now, so it'd be good to have the comparisons against a specific hash.
- [x] (Should also add the version info of the other frameworks there too)
- [x] On a separate note, I think it'll be a good idea to prune all the previews from gh-pages like we did previously before release.
- [x] Also, the NEWS section of the main documentation page is now fairly light on new features. Since we've added quite a lot, we should update that.

Optional
- [x] There are about 20 functions that don't have a docstring at present
- [x] PkgBenchmark on CI
- [x] Consider defaults for spaces. Do we use periodic = true (or false?) for all? Keep this consistent.

**Comment by Datseris** [comment]
I'll do the Developer docs

**Comment by Datseris** [comment]
> There are about 20 functions that don't have a docstring at present 

Are these _exported_ functions? Because this only matters for exported functions.

**Comment by Libbum** [comment]
No, but if we want to export some more comprehensive docs for contributors in the Developer documentation in the future, it may be a good on-boarding tool to keep up with this.

**Comment by Libbum** [comment]
Just making a note here that we should re-run benchmarks and update the relevant documentation page just before we tag v4. Things may be slightly different now, so it'd be good to have the comparisons against a specific hash.

(Should also add the version info of the other frameworks there too)
