### ISSUE TITLE
Create performance tips documentation page

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#454]
I'm starting this here to group various scattered tips until someone starts a pull request that adds the page.

- [ ] Avoid mixed type models due to inherent calls to dynamic dispatch, see #445 
- [ ] Use type-stable containers for `properties`, see #453 
- [ ] SOmething about immutable agent types, see #421

Feel free to leave comment below and I'll add it to the list.
